app:
    resource: '@AppBundle/Controller/'
    type: annotation
search:
    path:      /search/searchresult/{page}
    defaults:
        _controller: AppBundle:Controller:ResultController
        page:        1
        search:       "searchquery"
